
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  storageClassName: standard
  volumeName: host-pv 
  accessModes:
    - ReadWriteOnce
  resources: 
    requests:
      storage: 0.5Gi
